# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b5a944f7d07b97c142502ee3f6795c4f"
application_url = "https://mobility-textile-vbulletin-leasing.trycloudflare.com"
embedded = true
name = "shipping delivery"
handle = "shipping-delivery-3"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_locations,read_inventory,read_orders,read_products,read_shipping,write_shipping"

[auth]
redirect_urls = [
  "https://mobility-textile-vbulletin-leasing.trycloudflare.com/auth/callback",
  "https://mobility-textile-vbulletin-leasing.trycloudflare.com/auth/shopify/callback",
  "https://mobility-textile-vbulletin-leasing.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "test-jul1.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
